### PR TITLE
Fixes OSX travis build

### PR DESCRIPTION
**Pull request by tmortiboy**

### CODE REVIEW

**Comment by askoufis** [comment]
From that [issue](https://github.com/direnv/direnv/issues/210), it seems like most of the people who fixed it had pinned osx images, see [here](https://github.com/rudimeier/DirectionalityIndicator/blob/master/.travis.yml). Maybe we should try a few out and pin one that works?

**Comment by tmortiboy** [comment]
That is what I tried first `osx_image: beta-xcode6.1`, but maybe I should try a different image.
What you have linked to has `xcode7.3` and `xcode8.3`. You think its worth trying one of those?

**Comment by askoufis** [comment]
Worth a shot. Since we don't specify an image at the moment it's defaulting to 8.3 so maybe try 7.3.

**Comment by tmortiboy** [comment]
Cool, looks like 7.3 was the winner!

**Pull request merged**
